// mkerrors.sh -Wall -Werror -static -I/tmp/include
// Code generated by the command above; see README.md. DO NOT EDIT.

// +build sparc64,linux

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -Wall -Werror -static -I/tmp/include _const.go

package unix

import "syscall"

const (
	ASI_LEON_DFLUSH   = 0x11
	ASI_LEON_IFLUSH   = 0x10
	ASI_LEON_MMUFLUSH = 0x18

	EMT_TAGOVF = 0x1

	MAP_RENAME = 0x20

	PTRACE_GETFPAREGS  = 0x14
	PTRACE_GETFPREGS   = 0xe
	PTRACE_GETFPREGS64 = 0x19

	PTRACE_GETREGS64 = 0x16

	PTRACE_READDATA = 0x10
	PTRACE_READTEXT = 0x12

	PTRACE_SETFPAREGS  = 0x15
	PTRACE_SETFPREGS   = 0xf
	PTRACE_SETFPREGS64 = 0x1a

	PTRACE_SETREGS64 = 0x17

	PTRACE_SPARC_DETACH = 0xb

	PTRACE_WRITEDATA = 0x11
	PTRACE_WRITETEXT = 0x13
	PT_FP            = 0x48
	PT_G0            = 0x10
	PT_G1            = 0x14
	PT_G2            = 0x18
	PT_G3            = 0x1c
	PT_G4            = 0x20
	PT_G5            = 0x24
	PT_G6            = 0x28
	PT_G7            = 0x2c
	PT_I0            = 0x30
	PT_I1            = 0x34
	PT_I2            = 0x38
	PT_I3            = 0x3c
	PT_I4            = 0x40
	PT_I5            = 0x44
	PT_I6            = 0x48
	PT_I7            = 0x4c
	PT_NPC           = 0x8
	PT_PC            = 0x4
	PT_PSR           = 0x0
	PT_REGS_MAGIC    = 0x57ac6c00
	PT_TNPC          = 0x90
	PT_TPC           = 0x88
	PT_TSTATE        = 0x80
	PT_V9_FP         = 0x70
	PT_V9_G0         = 0x0
	PT_V9_G1         = 0x8
	PT_V9_G2         = 0x10
	PT_V9_G3         = 0x18
	PT_V9_G4         = 0x20
	PT_V9_G5         = 0x28
	PT_V9_G6         = 0x30
	PT_V9_G7         = 0x38
	PT_V9_I0         = 0x40
	PT_V9_I1         = 0x48
	PT_V9_I2         = 0x50
	PT_V9_I3         = 0x58
	PT_V9_I4         = 0x60
	PT_V9_I5         = 0x68
	PT_V9_I6         = 0x70
	PT_V9_I7         = 0x78
	PT_V9_MAGIC      = 0x9c
	PT_V9_TNPC       = 0x90
	PT_V9_TPC        = 0x88
	PT_V9_TSTATE     = 0x80
	PT_V9_Y          = 0x98
	PT_WIM           = 0x10
	PT_Y             = 0xc

	TCGETS2 = 0x402c540c

	TCSETS2 = 0x802c540d

	TCSETSF2 = 0x802c540f

	TCSETSW2 = 0x802c540e

	TIOCSTART = 0x2000746e

	TIOCSTOP = 0x2000746f

	__TIOCFLUSH = 0x80047410
)

// Errors
const (
	EPROCLIM = syscall.Errno(0x43)

	ERREMOTE = syscall.Errno(0x51)
)

// Signals
const (
	SIGEMT = syscall.Signal(0x7)

	SIGLOST = syscall.Signal(0x1d)
)

// Error table
var errorList = [...]struct {
	num  syscall.Errno
	name string
	desc string
}{
	{1, "EPERM", "operation not permitted"},
	{2, "ENOENT", "no such file or directory"},
	{3, "ESRCH", "no such process"},
	{4, "EINTR", "interrupted system call"},
	{5, "EIO", "input/output error"},
	{6, "ENXIO", "no such device or address"},
	{7, "E2BIG", "argument list too long"},
	{8, "ENOEXEC", "exec format error"},
	{9, "EBADF", "bad file descriptor"},
	{10, "ECHILD", "no child processes"},
	{11, "EAGAIN", "resource temporarily unavailable"},
	{12, "ENOMEM", "cannot allocate memory"},
	{13, "EACCES", "permission denied"},
	{14, "EFAULT", "bad address"},
	{15, "ENOTBLK", "block device required"},
	{16, "EBUSY", "device or resource busy"},
	{17, "EEXIST", "file exists"},
	{18, "EXDEV", "invalid cross-device link"},
	{19, "ENODEV", "no such device"},
	{20, "ENOTDIR", "not a directory"},
	{21, "EISDIR", "is a directory"},
	{22, "EINVAL", "invalid argument"},
	{23, "ENFILE", "too many open files in system"},
	{24, "EMFILE", "too many open files"},
	{25, "ENOTTY", "inappropriate ioctl for device"},
	{26, "ETXTBSY", "text file busy"},
	{27, "EFBIG", "file too large"},
	{28, "ENOSPC", "no space left on device"},
	{29, "ESPIPE", "illegal seek"},
	{30, "EROFS", "read-only file system"},
	{31, "EMLINK", "too many links"},
	{32, "EPIPE", "broken pipe"},
	{33, "EDOM", "numerical argument out of domain"},
	{34, "ERANGE", "numerical result out of range"},
	{36, "EINPROGRESS", "operation now in progress"},
	{37, "EALREADY", "operation already in progress"},
	{38, "ENOTSOCK", "socket operation on non-socket"},
	{39, "EDESTADDRREQ", "destination address required"},
	{40, "EMSGSIZE", "message too long"},
	{41, "EPROTOTYPE", "protocol wrong type for socket"},
	{42, "ENOPROTOOPT", "protocol not available"},
	{43, "EPROTONOSUPPORT", "protocol not supported"},
	{44, "ESOCKTNOSUPPORT", "socket type not supported"},
	{45, "ENOTSUP", "operation not supported"},
	{46, "EPFNOSUPPORT", "protocol family not supported"},
	{47, "EAFNOSUPPORT", "address family not supported by protocol"},
	{48, "EADDRINUSE", "address already in use"},
	{49, "EADDRNOTAVAIL", "cannot assign requested address"},
	{50, "ENETDOWN", "network is down"},
	{51, "ENETUNREACH", "network is unreachable"},
	{52, "ENETRESET", "network dropped connection on reset"},
	{53, "ECONNABORTED", "software caused connection abort"},
	{54, "ECONNRESET", "connection reset by peer"},
	{55, "ENOBUFS", "no buffer space available"},
	{56, "EISCONN", "transport endpoint is already connected"},
	{57, "ENOTCONN", "transport endpoint is not connected"},
	{58, "ESHUTDOWN", "cannot send after transport endpoint shutdown"},
	{59, "ETOOMANYREFS", "too many references: cannot splice"},
	{60, "ETIMEDOUT", "connection timed out"},
	{61, "ECONNREFUSED", "connection refused"},
	{62, "ELOOP", "too many levels of symbolic links"},
	{63, "ENAMETOOLONG", "file name too long"},
	{64, "EHOSTDOWN", "host is down"},
	{65, "EHOSTUNREACH", "no route to host"},
	{66, "ENOTEMPTY", "directory not empty"},
	{67, "EPROCLIM", "too many processes"},
	{68, "EUSERS", "too many users"},
	{69, "EDQUOT", "disk quota exceeded"},
	{70, "ESTALE", "stale file handle"},
	{71, "EREMOTE", "object is remote"},
	{72, "ENOSTR", "device not a stream"},
	{73, "ETIME", "timer expired"},
	{74, "ENOSR", "out of streams resources"},
	{75, "ENOMSG", "no message of desired type"},
	{76, "EBADMSG", "bad message"},
	{77, "EIDRM", "identifier removed"},
	{78, "EDEADLK", "resource deadlock avoided"},
	{79, "ENOLCK", "no locks available"},
	{80, "ENONET", "machine is not on the network"},
	{81, "ERREMOTE", "unknown error 81"},
	{82, "ENOLINK", "link has been severed"},
	{83, "EADV", "advertise error"},
	{84, "ESRMNT", "srmount error"},
	{85, "ECOMM", "communication error on send"},
	{86, "EPROTO", "protocol error"},
	{87, "EMULTIHOP", "multihop attempted"},
	{88, "EDOTDOT", "RFS specific error"},
	{89, "EREMCHG", "remote address changed"},
	{90, "ENOSYS", "function not implemented"},
	{91, "ESTRPIPE", "streams pipe error"},
	{92, "EOVERFLOW", "value too large for defined data type"},
	{93, "EBADFD", "file descriptor in bad state"},
	{94, "ECHRNG", "channel number out of range"},
	{95, "EL2NSYNC", "level 2 not synchronized"},
	{96, "EL3HLT", "level 3 halted"},
	{97, "EL3RST", "level 3 reset"},
	{98, "ELNRNG", "link number out of range"},
	{99, "EUNATCH", "protocol driver not attached"},
	{100, "ENOCSI", "no CSI structure available"},
	{101, "EL2HLT", "level 2 halted"},
	{102, "EBADE", "invalid exchange"},
	{103, "EBADR", "invalid request descriptor"},
	{104, "EXFULL", "exchange full"},
	{105, "ENOANO", "no anode"},
	{106, "EBADRQC", "invalid request code"},
	{107, "EBADSLT", "invalid slot"},
	{108, "EDEADLOCK", "file locking deadlock error"},
	{109, "EBFONT", "bad font file format"},
	{110, "ELIBEXEC", "cannot exec a shared library directly"},
	{111, "ENODATA", "no data available"},
	{112, "ELIBBAD", "accessing a corrupted shared library"},
	{113, "ENOPKG", "package not installed"},
	{114, "ELIBACC", "can not access a needed shared library"},
	{115, "ENOTUNIQ", "name not unique on network"},
	{116, "ERESTART", "interrupted system call should be restarted"},
	{117, "EUCLEAN", "structure needs cleaning"},
	{118, "ENOTNAM", "not a XENIX named type file"},
	{119, "ENAVAIL", "no XENIX semaphores available"},
	{120, "EISNAM", "is a named type file"},
	{121, "EREMOTEIO", "remote I/O error"},
	{122, "EILSEQ", "invalid or incomplete multibyte or wide character"},
	{123, "ELIBMAX", "attempting to link in too many shared libraries"},
	{124, "ELIBSCN", ".lib section in a.out corrupted"},
	{125, "ENOMEDIUM", "no medium found"},
	{126, "EMEDIUMTYPE", "wrong medium type"},
	{127, "ECANCELED", "operation canceled"},
	{128, "ENOKEY", "required key not available"},
	{129, "EKEYEXPIRED", "key has expired"},
	{130, "EKEYREVOKED", "key has been revoked"},
	{131, "EKEYREJECTED", "key was rejected by service"},
	{132, "EOWNERDEAD", "owner died"},
	{133, "ENOTRECOVERABLE", "state not recoverable"},
	{134, "ERFKILL", "operation not possible due to RF-kill"},
	{135, "EHWPOISON", "memory page has hardware error"},
}

// Signal table
var signalList = [...]struct {
	num  syscall.Signal
	name string
	desc string
}{
	{1, "SIGHUP", "hangup"},
	{2, "SIGINT", "interrupt"},
	{3, "SIGQUIT", "quit"},
	{4, "SIGILL", "illegal instruction"},
	{5, "SIGTRAP", "trace/breakpoint trap"},
	{6, "SIGABRT", "aborted"},
	{7, "SIGEMT", "EMT trap"},
	{8, "SIGFPE", "floating point exception"},
	{9, "SIGKILL", "killed"},
	{10, "SIGBUS", "bus error"},
	{11, "SIGSEGV", "segmentation fault"},
	{12, "SIGSYS", "bad system call"},
	{13, "SIGPIPE", "broken pipe"},
	{14, "SIGALRM", "alarm clock"},
	{15, "SIGTERM", "terminated"},
	{16, "SIGURG", "urgent I/O condition"},
	{17, "SIGSTOP", "stopped (signal)"},
	{18, "SIGTSTP", "stopped"},
	{19, "SIGCONT", "continued"},
	{20, "SIGCHLD", "child exited"},
	{21, "SIGTTIN", "stopped (tty input)"},
	{22, "SIGTTOU", "stopped (tty output)"},
	{23, "SIGIO", "I/O possible"},
	{24, "SIGXCPU", "CPU time limit exceeded"},
	{25, "SIGXFSZ", "file size limit exceeded"},
	{26, "SIGVTALRM", "virtual timer expired"},
	{27, "SIGPROF", "profiling timer expired"},
	{28, "SIGWINCH", "window changed"},
	{29, "SIGLOST", "power failure"},
	{30, "SIGUSR1", "user defined signal 1"},
	{31, "SIGUSR2", "user defined signal 2"},
}
