// go run mksysnum.go https://gitweb.dragonflybsd.org/dragonfly.git/blob_plain/HEAD:/sys/kern/syscalls.master
// Code generated by the command above; see README.md. DO NOT EDIT.

// +build amd64,dragonfly

package unix

// SYS_NOSYS = 0;  // { int nosys(void); } syscall nosys_args int

// SYS_NOSYS = 198;  // { int nosys(void); } __syscall __syscall_args int
