// go run mksysnum.go https://svn.freebsd.org/base/stable/11/sys/kern/syscalls.master
// Code generated by the command above; see README.md. DO NOT EDIT.

// +build 386,freebsd

package unix

// SYS_NOSYS = 0;  // { int nosys(void); } syscall nosys_args int
