// go run mksysnum.go /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/syscall.h
// Code generated by the command above; see README.md. DO NOT EDIT.

// +build amd64,darwin

package unix

const (
	SYS_KQUEUE_WORKLOOP_CTL       = 530
	SYS___MACH_BRIDGE_REMOTE_TIME = 531
)
