// cgo -godefs types_dragonfly.go | go run mkpost.go
// Code generated by the command above; see README.md. DO NOT EDIT.

// +build amd64,dragonfly

package unix

/* in_addr */

/* in6_addr */

/* in_addr */
/* in_addr */

/* in6_addr */

/* in6_addr */
